### PR TITLE
Feat/auto browser and bad query fallback

### PR DESCRIPTION
**Pull request by Kinfe123**
This change include 
- first , idk if this is something to add but i feel it some of peeps might need it but personally i dont use it a lot which is authomatically opening of browser (default) when we spin up the backend rust server - since it is not allowing me to run mutliple port if 3030 is already in use.. i just hard coded the port which the browser opens
- second - i have added the error message fallback like the image below for those that returns a error from backend . but this can be to have a stack trace to be displayed instead of blindly letting them know that something went wrong like ,something beyond syntax highlighting. 
image

### CODE REVIEW

**Comment by frectonz** [comment]
I like the automatically opening the URL thing, but i don't like the "No such resource returned ..." thing, i prefer the skeleton. If you remove the that i will merge this PR.

**Comment by Kinfe123** [comment]
do you skeleton would make sense for the users who aint know whether their query fails or not..

**Comment by frectonz** [comment]
ok yeah, we should do this

- show the loading skeleton, in the `loading` state
- show nothing, in the `error` state

Since i want people to directly type in their queries and have the data fetched automatically, i don't want them to be bombarded with a "No such resource error".

**Comment by Kinfe123** [comment]
yeah we can that by debouncing but yeah it is better to return a nothing.

**Comment by frectonz** [comment]
Yeah but don't add debouncing. I want querying to feel extremely fast, deboucing will just add a delay. Since people are running the server on their own local machine, we don't care about how many times they hit the `/query` route. Debouncing would have made sense if we were calling an external API.

**Comment by Kinfe123** [comment]
hmmm....makes sense , it is fixed by now

**Pull request merged**
